export const ACTIONS = {
  COURSES: "COURSES",
  SUPPORT: "SUPPORT",
  BACK: "BACK",
  ENROLL: "ENROLL",

  GOAL_JLPT: "GOAL_JLPT",
  GOAL_WORK: "GOAL_WORK",
  GOAL_STUDY: "GOAL_STUDY",
  GOAL_TRAVEL: "GOAL_TRAVEL",
  GOAL_ANIME: "GOAL_ANIME",
  GOAL_CONVERSATION: "GOAL_CONVERSATION",
  GOAL_CULTURE: "GOAL_CULTURE",
  GOAL_OTHER: "GOAL_OTHER",

  EXPERIENCE_YES: "EXPERIENCE_YES",
  EXPERIENCE_NO: "EXPERIENCE_NO",
  VIEW_COURSES: "VIEW_COURSES",

  ADMIN_REGISTRATIONS: "ADMIN_REGISTRATIONS",
} as const;

export type BotAction = (typeof ACTIONS)[keyof typeof ACTIONS];

export const BOT_STATES = {
  MAIN_MENU: "MAIN_MENU",
  COURSE_LIST: "COURSE_LIST",
  COURSE_DETAIL: "COURSE_DETAIL",
  SUPPORT: "SUPPORT",

  REGISTER_NAME: "REGISTER_NAME",
  REGISTER_PHONE: "REGISTER_PHONE",
} as const;

export type BotState = (typeof BOT_STATES)[keyof typeof BOT_STATES];
